// cribbed from https://github.com/rvdbreemen/OTGW-firmware/blob/dev/OTGW-Core.h
// and attributed to: https://github.com/jpraus/arduino-opentherm
//
	typedef enum OTtype_t { ot_f88, ot_s16, ot_s8s8, ot_u16, ot_u8u8, ot_flag8, ot_flag8flag8, ot_special, ot_flag8u8, ot_u8, ot_undef} OTtype_t; 
 	typedef enum OTmsgcmd_t { OT_READ, OT_WRITE, OT_RW, OT_UNDEF } OTmsgcmd_t;
	
	typedef struct OTlookup_t
    {
        int id;
        OTmsgcmd_t msgcmd;
        OTtype_t type;
        const char* label;
        const char* friendlyname;
        const char* unit;
    } OTlookup_t;

	//OTlookup_t OTlookupitem;

    const OTlookup_t OTmap[] = {
        {   0, OT_READ  , ot_flag8flag8,	"Status", "Master and Slave status", "" },
        {   1, OT_WRITE , ot_f88,        	"TSet", "Control setpoint", "deg C" },
        {   2, OT_WRITE , ot_flag8u8,    	"MasterConfigMemberIDcode", "Master Config / Member ID", "" },
        {   3, OT_READ  , ot_flag8u8,    	"SlaveConfigMemberIDcode", "Slave Config / Member ID", "" },
        {   4, OT_RW    , ot_u8u8,       	"Command", "Command-Code", "" },
		{   5, OT_READ  , ot_flag8u8,    	"ASFflags", "Application-specific fault", "" },
		{   6, OT_READ  , ot_flag8flag8,    "RBPflags", "Remote-parameter flags", "" },
		{   7, OT_WRITE , ot_f88,        	"CoolingControl", "Cooling control signal", "%" },
		{   8, OT_WRITE , ot_f88,        	"TsetCH2", "Control setpoint for 2e CH circuit", "deg C" },
		{   9, OT_READ  , ot_f88,        	"TrOverride", "Remote override room setpoint", "deg C" },
		{  10, OT_READ  , ot_u8u8,       	"TSP", "Number of TSPs", "" },
		{  11, OT_RW    , ot_u8u8,       	"TSPindexTSPvalue", "Index number / Value of referred-to transparent slave parameter", "" },
		{  12, OT_READ  , ot_u8u8,       	"FHBsize", "Size of Fault-History-Buffer supported by slave", "" },
		{  13, OT_READ  , ot_u8u8,       	"FHBindexFHBvalue", "Index number / Value of referred-to fault-history buffer entry", "" },
		{  14, OT_WRITE , ot_f88,        	"MaxRelModLevelSetting", "Maximum relative modulation level setting", "%" },
		{  15, OT_READ  , ot_u8u8,       	"MaxCapacityMinModLevel", "Maximum boiler capacity (kW) / Minimum boiler modulation level(%)", "kW/%" },
		{  16, OT_WRITE , ot_f88,        	"TrSet", "Room Setpoint", "deg C" },
		{  17, OT_READ  , ot_f88,        	"RelModLevel", "Relative Modulation Level", "%" },
		{  18, OT_READ  , ot_f88,        	"CHPressure", "CH water pressure", "bar" },
		{  19, OT_READ  , ot_f88,        	"DHWFlowRate", "DHW flow rate", "l/min" },
		{  20, OT_RW    , ot_special,    	"DayTime", "Day of Week and Time of Day", "" },
		{  21, OT_RW    , ot_u8u8,       	"Date", "Calendar date ", "" },
		{  22, OT_RW    , ot_u16,        	"Year", "Calendar year", "" },
		{  23, OT_WRITE , ot_f88,        	"TrSetCH2", "Room Setpoint CH2", "deg C" },
		{  24, OT_WRITE , ot_f88,        	"Tr", "Room Temperature", "deg C" },
		{  25, OT_READ  , ot_f88,        	"Tboiler", "Boiler water temperature", "deg C" },
		{  26, OT_READ  , ot_f88,        	"Tdhw", "DHW temperature", "deg C" },
		{  27, OT_READ  , ot_f88,        	"Toutside", "Outside temperature", "deg C" },
		{  28, OT_READ  , ot_f88,        	"Tret", "Return water temperature", "deg C" },
		{  29, OT_READ  , ot_f88,        	"Tsolarstorage", "Solar storage temperature", "deg C" },
		{  30, OT_READ  , ot_s16,        	"Tsolarcollector", "Solar collector temperature", "deg C" },
		{  31, OT_READ  , ot_f88,        	"TflowCH2", "Flow water temperature CH2", "deg C" },
		{  32, OT_READ  , ot_f88,        	"Tdhw2", "DHW2 temperature", "deg C" },
		{  33, OT_READ  , ot_s16,        	"Texhaust", "Exhaust temperature", "deg C" },
		{  34, OT_READ  , ot_f88, 	 	 	"Theatexchanger", "Boiler heat exchanger temperature", "deg C" },
		{  35, OT_READ  , ot_u8u8,	 	 	"FanSpeed", "Boiler fan speed and setpoint", "rpm" },
		{  36, OT_READ  , ot_f88, 			"ElectricalCurrentBurnerFlame", "Electrical current through burner flame", "uA" },
		{  37, OT_READ  , ot_f88, 			"TRoomCH2", "Room temperature for 2nd CH circuit", "deg C" },
		{  38, OT_READ  , ot_u8u8, 			"RelativeHumidity", "Relative Humidity", "%" },
		{  39, OT_UNDEF , ot_undef, 		"", "", "" },
		{  40, OT_UNDEF , ot_undef, 		"", "", "" },
		{  41, OT_UNDEF , ot_undef, 		"", "", "" },
		{  42, OT_UNDEF , ot_undef, 		"", "", "" },
		{  43, OT_UNDEF , ot_undef, 		"", "", "" },
		{  44, OT_UNDEF , ot_undef, 		"", "", "" },
		{  45, OT_UNDEF , ot_undef, 		"", "", "" },
		{  46, OT_UNDEF , ot_undef, 		"", "", "" },
		{  47, OT_UNDEF , ot_undef, 		"", "", "" },
		{  48, OT_READ  , ot_s8s8,        	"TdhwSetUBTdhwSetLB", "DHW setpoint upper & lower bounds for adjustment", "deg C" },
		{  49, OT_READ  , ot_s8s8,        	"MaxTSetUBMaxTSetLB", "Max CH water setpoint upper & lower bounds for adjustment", "deg C" },
		{  50, OT_READ  , ot_s8s8,        	"HcratioUBHcratioLB", "OTC heat curve ratio upper & lower bounds for adjustment", "deg C" },
		{  51, OT_READ  , ot_s8s8, 		  	"Remoteparameter4boundaries", "Remote parameter 4 boundaries", "" },
		{  52, OT_READ  , ot_s8s8, 		  	"Remoteparameter5boundaries", "Remote parameter 5 boundaries", "" },
		{  53, OT_READ  , ot_s8s8, 		  	"Remoteparameter6boundaries", "Remote parameter 6 boundaries", "" },
		{  54, OT_READ  , ot_s8s8, 		  	"Remoteparameter7boundaries", "Remote parameter 7 boundaries", "" },
		{  55, OT_READ  , ot_s8s8, 		  	"Remoteparameter8boundaries", "Remote parameter 8 boundaries", "" },
		{  56, OT_RW    , ot_f88,         	"TdhwSet", "DHW setpoint", "deg C" },	
		{  57, OT_RW    , ot_f88,         	"MaxTSet", "Max CH water setpoint", "deg C" },
		{  58, OT_RW    , ot_f88,         	"Hcratio", "OTC heat curve ratio", "deg C" },
		{  59, OT_RW 	, ot_f88, 		  	"Remoteparameter4", "Remote parameter 4", "" },
		{  60, OT_RW 	, ot_f88,         	"Remoteparameter5", "Remote parameter 5", "" },
		{  61, OT_RW 	, ot_f88,         	"Remoteparameter6", "Remote parameter 6", "" },
		{  62, OT_RW 	, ot_f88,         	"Remoteparameter7", "Remote parameter 7", "" },
		{  63, OT_RW 	, ot_f88,         	"Remoteparameter8", "Remote parameter 8", "" },
		{  64, OT_UNDEF , ot_undef, 		"", "", "" },
		{  65, OT_UNDEF , ot_undef, 		"", "", "" },
		{  66, OT_UNDEF , ot_undef, 		"", "", "" },
		{  67, OT_UNDEF , ot_undef, 		"", "", "" },
		{  68, OT_UNDEF , ot_undef, 		"", "", "" },
		{  69, OT_UNDEF , ot_undef, 		"", "", "" },
		{  70, OT_READ  , ot_flag8flag8,  	"StatusVH", "Status Ventilation/Heat recovery", "" },
		{  71, OT_WRITE , ot_u8, 			"ControlSetpointVH", "Control setpoint V/H", "" },
		{  72, OT_READ  , ot_flag8u8, 		"ASFFaultCodeVH", "Application-specific Fault Flags/Code V/H", "" },
		{  73, OT_READ  , ot_u16,		 	"DiagnosticCodeVH", "Diagnostic code V/H", "" },
		{  74, OT_READ  , ot_flag8u8,		"ConfigMemberIDVH", "Config/Member ID V/H", "" },
		{  75, OT_READ  , ot_f88, 			"OpenthermVersionVH", "OpenTherm version V/H", "" },
		{  76, OT_READ  , ot_u8u8, 			"VersionTypeVH", "Product version & type V/H", "" },
		{  77, OT_READ  , ot_u8, 			"RelativeVentilation", "Relative ventilation", "%" },
		{  78, OT_RW    , ot_u8u8, 			"RelativeHumidityExhaustAir", "Relative humidity exhaust air", "%" },
		{  79, OT_RW    , ot_u16, 			"CO2LevelExhaustAir", "CO2 level exhaust air", "ppm" },
 		{  80, OT_READ  , ot_f88, 			"SupplyInletTemperature", "Supply inlet temperature", "deg C" },
 		{  81, OT_READ  , ot_f88, 			"SupplyOutletTemperature", "Supply outlet temperature", "deg C" },
 		{  82, OT_READ  , ot_f88, 			"ExhaustInletTemperature", "Exhaust inlet temperature", "deg C" },
 		{  83, OT_READ  , ot_f88, 			"ExhaustOutletTemperature", "Exhaust outlet temperature", "deg C" },
		{  84, OT_READ  , ot_u16, 			"ActualExhaustFanSpeed", "Actual exhaust fan speed", "rpm" },
		{  85, OT_READ  , ot_u16, 			"ActualSupplyFanSpeed", "Actual supply fan speed", "rpm" },
		{  86, OT_READ  , ot_flag8flag8, 	"RemoteParameterSettingVH", "Remote Parameter Setting V/H", "" },
		{  87, OT_RW 	, ot_u8, 			"NominalVentilationValue", "Nominal Ventilation Value", "" },
		{  88, OT_READ  , ot_u8u8, 			"TSPNumberVH", "TSP Number V/H", "" },
		{  89, OT_RW    , ot_u8u8, 			"TSPEntryVH", "TSP setting V/H", "" },
		{  90, OT_READ  , ot_u8u8, 			"FaultBufferSizeVH", "Fault Buffer Size V/H", "" },
		{  91, OT_READ  , ot_u8u8, 			"FaultBufferEntryVH", "Fault Buffer Entry V/H", "" },
		{  92, OT_UNDEF , ot_undef, 		"", "", "" },
		{  93, OT_UNDEF , ot_undef, 		"", "", "" },
		{  94, OT_UNDEF , ot_undef, 		"", "", "" },
		{  95, OT_UNDEF , ot_undef, 		"", "", "" },
		{  96, OT_UNDEF , ot_undef, 		"", "", "" },
		{  97, OT_UNDEF , ot_undef, 		"", "", "" },
		{  98, OT_READ  , ot_u8u8, 			"RFstrengthbatterylevel", "RF strength and battery level", "" },
		{  99, OT_READ  , ot_u8u8, 			"OperatingMode_HC1_HC2_DHW", "Operating Mode HC1, HC2/ DHW", "" },
		{ 100, OT_READ  , ot_flag8,       	"RoomRemoteOverrideFunction", "Function of manual and program changes in master and remote room setpoint.", "" },
		{ 101, OT_READ  , ot_flag8flag8, 	"SolarStorageMaster", "Solar Storage Master mode", "" },
		{ 102, OT_READ  , ot_flag8u8,    	"SolarStorageASFflags", "Solar Storage Application-specific flags and OEM fault", "" },
        { 103, OT_READ  , ot_flag8u8,    	"SolarStorageSlaveConfigMemberIDcode", "Solar Storage Slave Config / Member ID", "" },
		{ 104, OT_READ  , ot_u8u8,        	"SolarStorageVersionType", "Solar Storage product version number and type", "" },
		{ 105, OT_READ  , ot_u8u8,       	"SolarStorageTSP", "Solar Storage Number of Transparent-Slave-Parameters supported", "" },
		{ 106, OT_RW    , ot_u8u8,       	"SolarStorageTSPindexTSPvalue", "Solar Storage Index number / Value of referred-to transparent slave parameter", "" },
		{ 107, OT_READ  , ot_u8u8,       	"SolarStorageFHBsize", "Solar Storage Size of Fault-History-Buffer supported by slave", "" },
		{ 108, OT_READ  , ot_u8u8,       	"SolarStorageFHBindexFHBvalue", "Solar Storage Index number / Value of referred-to fault-history buffer entry", "" },
		{ 109, OT_READ  , ot_u16, 			"ElectricityProducerStarts", "Electricity producer starts", "" },
		{ 110, OT_READ  , ot_u16, 			"ElectricityProducerHours", "Electricity producer hours", "" },
		{ 111, OT_READ  , ot_u16, 			"ElectricityProduction", "Electricity production", "" },
		{ 112, OT_READ  , ot_u16, 			"CumulativElectricityProduction", "Cumulativ Electricity production", "" },
		{ 113, OT_RW    , ot_u16,         	"BurnerUnsuccessfulStarts", "Unsuccessful burner starts", "" },
		{ 114, OT_RW    , ot_u16,         	"FlameSignalTooLow", "Flame signal too low count", "" },
		{ 115, OT_READ  , ot_u16,         	"OEMDiagnosticCode", "OEM-specific diagnostic/service code", "" },
		{ 116, OT_RW    , ot_u16,         	"BurnerStarts", "Burner starts", "" },
		{ 117, OT_RW    , ot_u16,         	"CHPumpStarts", "CH pump starts", "" },
		{ 118, OT_RW    , ot_u16,         	"DHWPumpValveStarts", "DHW pump/valve starts", "" },
		{ 119, OT_RW    , ot_u16,         	"DHWBurnerStarts", "DHW burner starts", "" },
		{ 120, OT_RW    , ot_u16,         	"BurnerOperationHours", "Burner operation hours", "hrs" },
		{ 121, OT_RW    , ot_u16,         	"CHPumpOperationHours", "CH pump operation hours", "hrs" },
		{ 122, OT_RW    , ot_u16,         	"DHWPumpValveOperationHours", "DHW pump/valve operation hours", "hrs" },
		{ 123, OT_RW    , ot_u16,         	"DHWBurnerOperationHours", "DHW burner operation hours", "hrs" },
		{ 124, OT_READ  , ot_f88,			"OpenThermVersionMaster", "Master Version OpenTherm Protocol Specification", "" },
		{ 125, OT_READ  , ot_f88,			"OpenThermVersionSlave", "Slave Version OpenTherm Protocol Specification", "" },
		{ 126, OT_READ  , ot_u8u8,			"MasterVersion", "Master product version number and type", "" },
		{ 127, OT_READ  , ot_u8u8,			"SlaveVersion", "Slave product version number and type", "" },
		{ 128, OT_UNDEF , ot_undef,			"", "", "" },
		{ 129, OT_UNDEF , ot_undef, 		"", "", "" },
		{ 130, OT_UNDEF , ot_undef, 		"", "", "" },
		{ 131, OT_RW 	, ot_u8u8, 			"RemehadFdUcodes", "Remeha dF-/dU-codes", "" },
		{ 132, OT_READ 	, ot_u8u8, 			"RemehaServicemessage", "Remeha Servicemessage", "" },
		{ 133, OT_READ 	, ot_u8u8, 			"RemehaDetectionConnectedSCU", "Remeha detection connected SCU’s", "" },
		// all data ids are not defined above are resevered for future use
		// A foney id is used for sensors on GPIO ports, 
 		// 245 for counter and 
 		// 246 for Dallas temperature sensors
	};
